name: mediaexplant
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  http: ^1.3.0
  dio: ^5.4.0
  url_launcher: ^6.1.7
  lottie: ^3.3.1
  flutter_svg: ^2.0.9
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  permission_handler: ^11.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/Animation_1742097390792.json
    - assets/animations/Animation_1742098657264.json
    - assets/animations/Animation_1742099923119.json
    - assets/animations/Animation_1742101335442.json
    - assets\animations\Animation_1742111248256.json
    - assets\images\app_logo.svg