name: mediaexplant
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.15
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  lottie: ^3.3.1
  permission_handler: ^11.4.0
  provider: ^6.0.5
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animations/Animation_1742097390792.json
    - assets/animations/Animation_1742098657264.json
    - assets/animations/Animation_1742099923119.json
    - assets/animations/Animation_1742101335442.json
    - assets\animations\Animation_1742111248256.json
    - assets\animations\Welcome.json
    - assets\animations\Animation_1742404418041.json
    - assets\animations\Animation_1742404469999.json
    - assets\images\app_logo.svg
