name: mediaexplant
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  http: ^0.13.5
  dio: ^5.4.0
  url_launcher: ^6.1.7
  lottie: ^2.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/Animation_1742097390792.json
    - assets/animations/Animation_1742098657264.json
    - assets/animations/Animation_1742099923119.json
    - assets/animations/Animation_1742101335442.json
