name: mediaexplant
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.15
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.4.0
  dio: ^5.8.0+1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_html: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^19.1.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.1
  get: null
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  lottie: ^3.3.1
  open_file: ^3.5.10
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  pdfx: ^2.9.1
  permission_handler: ^12.0.0+1
  provider: ^6.0.5
  shared_preferences: ^2.5.2
  timeago: ^3.7.1
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/Animation_1742097390792.json
    - assets/animations/Animation_1742098657264.json
    - assets/animations/Animation_1742099923119.json
    - assets/animations/Animation_1742101335442.json
    - assets\animations\Animation_1742111248256.json
    - assets\animations\Welcome.json
    - assets\animations\Animation_1742404418041.json
    - assets\animations\Animation_1742404469999.json
    - assets\images\app_logo.png
